import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually
  textbookSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics Textbook',
      items: [
        {
          type: 'category',
          label: 'ROS 2 Foundations',
          items: [
            'chapters/ros2/ch1-introduction',
            'chapters/ros2/ch2-nodes-topics-services-actions',
            'chapters/ros2/ch3-python-development'
          ],
        },
        {
          type: 'category',
          label: 'Gazebo/Unity Simulation',
          items: [
            'chapters/gazebo-unity/ch4-introduction-to-gazebo',
            'chapters/gazebo-unity/ch5-robot-modeling',
            'chapters/gazebo-unity/ch6-basic-robot-control'
          ],
        },
        {
          type: 'category',
          label: 'NVIDIA Isaac',
          items: [
            'chapters/nvidia-isaac/ch7-introduction-to-isaac-sim',
            'chapters/nvidia-isaac/ch8-advanced-simulation-techniques'
          ],
        },
        {
          type: 'category',
          label: 'Vision-Language-Action (VLA)',
          items: [
            'chapters/vla/ch9-perception-for-humanoids',
            'chapters/vla/ch10-motion-planning-control',
            'chapters/vla/ch11-human-robot-interaction-ethics',
            'chapters/vla/ch12-emerging-trends'
          ],
        },
      ],
    },
  ],
};

export default sidebars;